package com.taiyu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-11-12T16:05:15.788+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://webService.taiyu.com/", name = "NewDataCallback")
@XmlSeeAlso({ObjectFactory.class})
public interface NewDataCallback {

    @WebMethod(operationName = "dataImportXml_zip")
    @RequestWrapper(localName = "dataImportXml_zip", targetNamespace = "http://webService.taiyu.com/", className = "com.taiyu.DataImportXmlZip")
    @ResponseWrapper(localName = "dataImportXml_zipResponse", targetNamespace = "http://webService.taiyu.com/", className = "com.taiyu.DataImportXmlZipResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String dataImportXmlZip(
        @WebParam(name = "arg0", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "http://webService.taiyu.com/")
        byte[] arg2,
        @WebParam(name = "arg3", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "saveDzgwData", targetNamespace = "http://webService.taiyu.com/", className = "com.taiyu.SaveDzgwData")
    @ResponseWrapper(localName = "saveDzgwDataResponse", targetNamespace = "http://webService.taiyu.com/", className = "com.taiyu.SaveDzgwDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String saveDzgwData(
        @WebParam(name = "data_name", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String dataName,
        @WebParam(name = "data_path", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String dataPath,
        @WebParam(name = "dept_code", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String deptCode,
        @WebParam(name = "file_num", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String fileNum
    );

    @WebMethod
    @RequestWrapper(localName = "newDataCallback", targetNamespace = "http://webService.taiyu.com/", className = "com.taiyu.NewDataCallback_Type")
    @ResponseWrapper(localName = "newDataCallbackResponse", targetNamespace = "http://webService.taiyu.com/", className = "com.taiyu.NewDataCallbackResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String newDataCallback(
        @WebParam(name = "data_name", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String dataName,
        @WebParam(name = "time_stamp", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String timeStamp,
        @WebParam(name = "data_path", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String dataPath,
        @WebParam(name = "qym", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String qym,
        @WebParam(name = "dept_code", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String deptCode,
        @WebParam(name = "file_num", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String fileNum,
        @WebParam(name = "md5", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String md5,
        @WebParam(name = "arg", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String arg
    );

    @WebMethod
    @RequestWrapper(localName = "saveZjgData", targetNamespace = "http://webService.taiyu.com/", className = "com.taiyu.SaveZjgData")
    @ResponseWrapper(localName = "saveZjgDataResponse", targetNamespace = "http://webService.taiyu.com/", className = "com.taiyu.SaveZjgDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String saveZjgData(
        @WebParam(name = "data_name", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String dataName,
        @WebParam(name = "data_path", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String dataPath,
        @WebParam(name = "dept_code", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String deptCode,
        @WebParam(name = "file_num", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String fileNum,
        @WebParam(name = "b64SignedData", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String b64SignedData,
        @WebParam(name = "b64SignCert", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String b64SignCert,
        @WebParam(name = "jslx", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String jslx,
        @WebParam(name = "hdjklj", targetNamespace = "http://webService.taiyu.com/")
        java.lang.String hdjklj
    );
}
